- ja/sponsors/index.html
> rm nakayama-san's blog link

- _candidates_en/AndreaPEruffo_1.md
> Add "Principled SBT"

- _candidates_en/LarsHupel_1.md
> add English version of Lars Hupel's proposal

- _candidates_en/Himanshu_2.md
> add English version of Himanshu_2

- _candidates_en/JakubKozlowski_1.md
> add English version of JakubKozlowski_1

- _candidates_en/Himanshu_3.md
> add English version of Himanshu_3

- _candidates_ja/JonPretty_1.md
> JonPretty 和訳

- _layouts/default_en.html
- _layouts/default_ja.html
- index.html
> Google search consoleによるチェックのためのサイト所有権確認のタグを追加

- _candidates_en/RaulPiaggio_1.md
> Add candidates_en/RaulPiaggio_1.md

- _candidates_ja/RaulPiaggio_1.md
> 和訳: RaulPiaggio_1.md

- _candidates_ja/LarsHupel_2.md
> LarsHupel_2.md 和訳

- _candidates_ja/Himanshu_2.md
> Himanshu さんによる「Accelerating Performance of ML Applications with KSAI」和訳

- _candidates_en/BlastHardchese_1.md
> add English version of BlastHardchese_1.md

- _candidates_ja/qtamaki_1.md
> Add candidates_ja/qtamaki_1.md

- _candidates_en/AdilAkhter_1.md
fix https://github.com/scalajp/2019.scalamatsuri.org/issues/111
speaker_experienceが多すぎるので、最初の3つだけにしてます。
> Adil Akhterさん英語版掲載

- _candidates_en/JakubKozlowski_2.md
> Add en/JakubKozlowski_2

- _candidates_en/JakubKozlowski_3.md
> Add en/JakubKozlowski_3

- _candidates_en/Taylor_1.md
> Add en/Taylor_1

- _candidates_en/RubenResino_1.md
> Add en/RubenResino_1

- _candidates_en/RubenResino_2.md
> Add en/RubenResino_2

- _candidates_en/DavidvanGeest_1.md
> Add en/DavidvanGeest_1

- _candidates_en/JustinKaeser_1.md
> Add en/JustinKaeser_1

- _candidates_en/AnneDeCusatis_1.md
> Add en/AnneDeCusatis_1

- _candidates_ja/KazuhiroIchikawa_1.md
> Add ja/KazuhiroIchikawa_1

- _candidates_ja/ShinichiMorimoto_1.md
> Add ja/ShinichiMorimoto_1

- _candidates_ja/YoshiteruTakeshita_1.md
> Add ja/YoshiteruTakeshita_1

- _candidates_en/HarmeetSingh_1.md
> Add en/HarmeetSingh_1

- _candidates_en/GuillemIscla_1.md
> Add en/GuillemIscla_1

- _candidates_ja/MotoyasuSaburi_1.md
> Add ja/MotoyasuSaburi_1

- _candidates_en/ZahariDichev_1.md
> Add en/ZahariDichev_1

- _candidates_en/ZahariDichev_2.md
> Add en/ZahariDichev_2

- _candidates_ja/MotoyasuSaburi_1.md
https://github.com/scalajp/2019.staff/issues/137 (スタッフしか見れません。ご容赦ください。)
Twitterのアカウントを削除したいとのことなので、削除します。
> 問い合わせにより、twitterのリンクを削除

- _candidates_en/MariaLiviaChiorean_1.md
> Add en/MariaLiviaChiorean_1

- _candidates_en/HarmeetSingh_2.md
> Add en/HarmeetSingh_2

- _candidates_en/HarmeetSingh_3.md
> Add en/HarmeetSingh_3

- _candidates_en/MikhailLimanskiy_1.md
> Add en/MikhailLimanskiy_1

- _candidates_en/FlavioBrasil_1.md
> Add en/FlavioBrasil_1

- _candidates_ja/masahito_1.md
> Add ja/masahito_1

- _candidates_en/MikolajKoziarkiewicz_1.md
> Add en/MikolajKoziarkiewicz_1

- _candidates_en/MikolajKoziarkiewicz_2.md
> Add en/MikolajKoziarkiewicz_2

- _candidates_ja/YoshihiroYoshida_1.md
> Add ja/YoshihiroYoshida_1

- _candidates_ja/YoshitakaFujii_1.md
> Add ja/YoshitakaFujii_1

- _candidates_ja/JunichiKato_1.md
> Add ja/JunichiKato_1

- _candidates_ja/HirokiFujino_1.md
> Add ja/HirokiFujino_1

- _candidates_ja/osiire_1.md
> Add ja/osiire_1

- _candidates_en/NicolasJorand_1.md
> Add en/NicolasJorand_1

- _candidates_ja/k_bigwheel_1.md
> Add ja/k_bigwheel_1

- _candidates_ja/YoshihiroYoshida_1.md
今回、Cfpを応募させていただきました、吉田芳弘と申します。
audienceを Beginner から Intermediate に変更をお願いします。
下記のisuueの方にもコメントを書かせていただきました。
https://github.com/scalajp/2019.scalamatsuri.org/issues/254
よろしくお願いします。
> Change audience: Beginner to Intermediate

- _candidates_en/ChetanKhatri_2.md
> Add en/ChetanKhatri_2

- _candidates_en/ZachMcCoy_2.md
> Add en/ZachMcCoy_2

- _candidates_en/ZachMcCoy_1.md
> Add en/ZachMcCoy_1

- _candidates_en/ChetanKhatri_1.md
> Add en/ChetanKhatri_1

- _candidates_en/GuillemIscla_2.md
> Add en/GuillemIscla_2

- _candidates_en/MahmoudAbdelghany_1.md
> Add en/MahmoudAbdelghany_1

- _candidates_ja/Hayabusa_1.md
> Add ja/Hayabusa_1

- _candidates_ja/HonMarkHunt_1.md
> Add ja/HonMarkHunt_1

- _candidates_ja/omiend_1.md
> Add ja/omiend_1

- _candidates_ja/TaketoIkeda_2.md
> Add ja/TaketoIkeda_2

- _candidates_en/MichalPlachta_1.md
> add en/MichalPlachta_1

- _candidates_en/qtamaki_1.md
> translate Tamaki-san's abstract

- _candidates_en/KazuhiroIchikawa_1.md
> translate Ichikawa-san's abstract

- _candidates_en/kiris_1.md
> translate Kiris-san's abstract

- _candidates_en/MasayaDake_1.md
> translate Dake-san's abstract

- _candidates_en/ShinichiMorimoto_1.md
> translate Morimoto-san's abstract

- _candidates_en/YoshiteruTakeshita_1.md
> translate Takeshita-san's abstract

- _candidates_en/TaketoIkeda_1.md
> translate Ikeda-san's abstract

- _candidates_en/petitviolet_1.md
> translate Komurasaki-san's abstract

- _candidates_en/TaketoIkeda_2.md
> add English translation of TaketoIkeda_2.md

- _candidates_en/MotoyasuSaburi_1.md
> translate Saburi-san's abstract

- _candidates_en/masahito_1.md
> translate Masato Nakamura-san's abstract

- _candidates_en/YoshihiroYoshida_1.md
> translate Yoshihiro Yoshida-san's abstract

- _candidates_en/JunichiKato_1.md
> translate Kato-san's abstract

- _candidates_en/HirokiFujino_1.md
> translate Fujino-san's abstract

- _candidates_en/k_bigwheel_1.md
> translate k_bigwheel's abstract

- _candidates_en/Hayabusa_1.md
> translate Hayabusa-san's abstract

- _candidates_en/HonMarkHunt_1.md
> translate HonMarkHunt-san's abstract

- _candidates_en/omiend_1.md
> translate Omiend-san's abstract

- _candidates_ja/TakahiroSatoh_1.md
> Add ja/TakahiroSatoh_1

- _candidates_ja/shinharad_1.md
> Add ja/shinharad_1

- _candidates_ja/MasateruNishimura_1.md
> Add ja/MasateruNishimura_1

- _candidates_ja/GuillemIscla_1.md
> Add ja/GuillemIscla_1

- _candidates_ja/MichalPlachta_1.md
> add ja/MichalPlachta_1

- _candidates_en/YoshitakaFujii_1.md
> translate YoshitakaFujii_1

- _candidates_en/RubenResino_1.md
- _candidates_en/RubenResino_2.md
> Fix icon URL

- _candidates_ja/jooohn1234_1.md
This PR is related to "CFPの掲載@和訳: jooohn1234 さんによる「Play with implicit!」 #420"
> Add jooohn1234_1.md to _candidates_ja

- _candidates_ja/KojiAGAWA_1.md
> Add ja/KojiAGAWA_1

- _candidates_en/jooohn1234_1.md
> add joohn1234_1

- _candidates_ja/RubenResino_2.md
> Add ja/RubenResino2.md

- _data/nav_en.yml
- _data/nav_ja.yml
- _includes/index/en/thanks_for_cfp.html
- _includes/index/ja/thanks_for_cfp.html
- css/common.css
- en/candidates/index.html
- index.html
- index_en.html
- ja/candidates/index.html
CFPの応募は2/2までなので、そのタイミングで応募ページを閉じる
竹下が時間にマージするので確認してくれた人はApproveだけお願いします。
> CFPの応募を閉じる

- _candidates_ja/YuyaOnuma_1.md
> Add ja/YuyaOnuma_1

- _candidates_ja/kmizu_1.md
> Add ja/kmizu_1

- _candidates_ja/piyo7_1.md
> Add ja/piyo7_1

- _candidates_ja/NobuhikoHosonishi_1.md
> Add ja/NobuhikoHosonishi_1

- _candidates_en/MikhailMutcianko_1.md
> Add en/MikhailMutcianko_1

- _candidates_ja/JiroHiraiwa_1.md
> Add ja/JiroHiraiwa_1

- _candidates_ja/kiris_2.md
> Add ja/kiris_2

- _candidates_ja/TomoyukiShimomuraYoshimasaTanabe_1.md
> Add ja/TomoyukiShimomuraYoshimasaTanabe_1

- _candidates_ja/HarmeetSingh_1.md
> Add ja/HarmeetSingh_1.md

- _candidates_ja/ZachMcCoy_2.md
> Add _candidates_ja/ZachMcCoy_2.md

- _candidates_en/ChanglinLi_1.md
> Add en/ChanglinLi_1

- _candidates_ja/YuichiMaekawa_1.md
> Add ja/YuichiMaekawa_1

- _candidates_en/ErwanLoisant_1.md
> Add en/ErwanLoisant_1

- _candidates_en/MatanKeidar_1.md
> Add en/MatanKeidar_1

- _candidates_ja/ma2k8_1.md
> Add ja/ma2k8_1

- _candidates_en/JoanGoyeau_1.md
> Add en/JoanGoyeau_1

- _candidates_en/IaroslavZeigerman_1.md
> Add en/IaroslavZeigerman_1

- _candidates_en/ColtFrederickson_1.md
> Add en/ColtFrederickson_1

- _candidates_en/SebastienDoeraene_1.md
> Add en/SebastienDoeraene_1

- _candidates_en/SebastienDoeraene_2.md
> Add en/SebastienDoeraene_2

- _candidates_en/ColtFrederickson_2.md
> Add en/ColtFrederickson_2

- _candidates_en/WilberChao_1.md
> Add en/WilberChao_1

- _candidates_en/WilberChao_2.md
> Add en/WilberChao_2

- _candidates_en/SahilSawhney_1.md
> Add en/SahilSawhney_1

- _candidates_en/SahilSawhney_2.md
> Add en/SahilSawhney_2

- _candidates_en/ChanglinLi_2.md
> Add en/ChanglinLi_2

- _candidates_ja/TaroLSaito_1.md
> Add ja/TaroLSaito_1

- _candidates_en/AlexanderKonovalov_1.md
> Add en/AlexanderKonovalov_1

- _candidates_en/AlexanderKonovalov_2.md
> Add en/AlexanderKonovalov_2

- _candidates_en/PrabhatKashyap_1.md
> Add en/PrabhatKashyap_1

- _candidates_en/EugeneYokota_1.md
> Add en/EugeneYokota_1

- _candidates_en/EugeneYokota_2.md
> Add en/EugeneYokota_2

- _candidates_ja/Himanshu_3.md
> Add ja/Himanshu_3.md

- _candidates_ja/mdstoy_1.md
> Add ja/mdstoy_1

- _candidates_ja/negokaz_1.md
> Add ja/negokaz_1

- _candidates_en/EugeneYokota_3.md
> Add en/EugeneYokota_3

- _candidates_ja/ShunsukeTadokoro_1.md
> Add ja/ShunsukeTadokoro_1

- _candidates_en/AlexanderKonovalov_3.md
> Add en/AlexanderKonovalov_3

- _candidates_ja/MitsuhiroShibuya_1.md
> Add ja/MitsuhiroShibuya_1

- _candidates_ja/ShunsukeTadokoro_2.md
> Add ja/ShunsukeTadokoro_2

- _candidates_ja/TaroLSaito_2.md
> Add ja/TaroLSaito_2

- _candidates_ja/tkt_horikoshi_1.md
> Add ja/tkt_horikoshi_1

- _candidates_ja/halcat0x15a_1.md
> Add ja/halcat0x15a_1

- _candidates_ja/ManabuNakamura_1.md
> Add ja/ManabuNakamura_1

- _candidates_ja/TakumiKadowaki_1.md
> Add ja/TakumiKadowaki_1

- _candidates_ja/KenichiTanga_1.md
> Add ja/KenichiTanga_1

- _candidates_ja/TakumiKadowaki_2.md
> Add ja/TakumiKadowaki_2

- _candidates_ja/ToyoshimaMasaki_1.md
> Add ja/ToyoshimaMasaki_1

- _candidates_en/SahilSawhney_3.md
> Add en/SahilSawhney_3

- _candidates_ja/AsamiAbe_1.md
> Add ja/AsamiAbe_1

- _candidates_en/AnneDeCusatis_1.md
The form I submitted for the CFP had a link that didn't work. This link should work. Thanks!
> Update my icon link to working image link

- _candidates_en/ManabuNakamura_1.md
> add english translation of ManabuNakamura_1

- _candidates_en/halcat0x15a_1.md
> add English translation of halcat0x15a

- _candidates_en/shinharad_1.md
> translate shinharad-san's abstract

- _candidates_en/MasateruNishimura_1.md
> touch up Nishimura-san's abstract

- _candidates_en/KojiAGAWA_1.md
> translate Agawa-san's abstract

- _candidates_en/piyo7_1.md
> touch up piyo7-san's abstract

- _candidates_en/YuichiMaekawa_1.md
> translate Maekawa-san's abstract

- _candidates_en/ma2k8_1.md
> translate ma2k8-san's abstract

- _candidates_en/mdstoy_1.md
> translate Takeda-san's abstract

- _candidates_en/negokaz_1.md
> translate nogokaz-san's abstract

- _candidates_en/TaroLSaito_1.md
> Saito-san's abstract

- _candidates_en/ShunsukeTadokoro_1.md
> translate Tadokoro-san's abstract

- _candidates_en/MitsuhiroShibuya_1.md
> touch up Shibuya-san's abstract

- _candidates_en/ShunsukeTadokoro_2.md
> translate Tadokoro-san's second abstract

- _candidates_en/TaroLSaito_2.md
> Saito-san's second abstract

- _candidates_en/tkt_horikoshi_1.md
> translate tkt_horikoshi-san's abstract

- _candidates_en/TakumiKadowaki_1.md
> translate Kadowaki-san's abstract

- _candidates_en/KenichiTanga_1.md
> translate Tanga-san's abstract

- _candidates_en/ToyoshimaMasaki_1.md
> translate Toyoshima-san's abstract

- _candidates_en/ToyoshimaMasaki_2.md
> translate Toyoshima-san's second abstract

- _candidates_en/AsamiAbe_1.md
> translate Kinoko-san's abstract

- _candidates_en/YuyaOnuma_1.md
> translate Onuma-san's abstract

- _layouts/candidates_en.html
- _layouts/candidates_ja.html
> CFP詳細に残ってた応募リンクの削除

- _candidates_en/BlastHardchese_1.md
- _candidates_ja/BlaskHardchese_1.md
> fix BlastHardchese_1

- _candidates_en/JiroHiraiwa_1.md
> translate Hiraiwa-san's abstract

- _candidates_en/TomokiFuruhashi_1.md
> translate Furuhashi-san's abstract

- _candidates_en/TomoyukiShimomuraYoshimasaTanabe_1.md
> translate Shimomura-san and Tanabe-san's abstract

- _candidates_en/TakumiKadowaki_2.md
> translate Kadowaki-san's second abstract

- _candidates_ja/AdilAkhter_1.md
> translate Adil Akhter's abstract

- _candidates_ja/JakubKozlowski_2.md
> translate Jakub Kozłowski's abstract

- _candidates_ja/AnneDeCusatis_1.md
> translate Anne DeCusatis's abstract

- _candidates_ja/RubenResino_1.md
> translate Rubén Resino's abstract

- _candidates_en/LongCao_1.md
> Add en/LongCao_1

- _candidates_ja/ChanglinLi_1.md
ref: https://github.com/scalajp/2019.scalamatsuri.org/issues/497
> translate ja/ChanglinLi_1

- _candidates_ja/ChanglinLi_2.md
ref: https://github.com/scalajp/2019.scalamatsuri.org/issues/495
> translate ja/ChanglinLi_2

- _candidates_ja/DavidvanGeest_1.md
> translate Davidvan Geest's abstract

- _candidates_ja/EmilianoMartinez_1.md
> translate Emiliano Martinez's abstract

- _candidates_ja/SahilSawhney_3.md
> Added ja/SahilSawhney_3.md

- _candidates_ja/SahilSawhney_2.md
> Added ja/SahilSawhney_2

- _candidates_ja/PrabhatKashyap_1.md
> Added ja/PrabhatKashyap_1

- _candidates_ja/GuillemIscla_2.md
> Add ja/GuillemIscla_2

- _candidates_ja/AlexanderKonovalov_3.md
> Added ja/AlexanderKonovalov_3

- _candidates_en/tanishiking_1.md
- _candidates_ja/tanishiking_1.md
@smroy 
please review the English one (_candidates_en/tanishiking_1.md) 
ref #428 , #429
> fix #428 fix #429 / add tanishiking-san's proposal

- _candidates_ja/MikolajKoziarkiewicz_1.md
> Add _candidates_ja/MikolajKoziarkiewicz_1.md

- _candidates_ja/ErwanLoisant_1.md
> add ja/ErwanLoisant_1

- _candidates_ja/LongCao_1.md
Fixes #685 
ref. https://github.com/scalajp/2019.scalamatsuri.org/blob/master/_candidates_en/LongCao_1.md
>  translate Long Cao's abstract

- _candidates_ja/HarmeetSingh_2.md
> Add HarmeetSingh_2 ja

- _candidates_ja/IaroslavZeigerman_1.md
> translate Iaroslav Zeigerman's abstract

- _candidates_ja/JulienTournay_1.md
> translate Julien Tournay's abstract

- _candidates_ja/EugeneYokota_1.md
> translate Eugene's first abstract

- _candidates_ja/EugeneYokota_2.md
> translate Eugene's second abstract

- _candidates_ja/NicolasJorand_1.md
> Add NicolasJorand_1 ja

- _candidates_ja/MikhailLimanskiy_1.md
> add ja/MikhailLimanskiy_1

- _candidates_ja/AlexanderKonovalov_1.md
> add AlexanderKonovalov_1 ja

- _candidates_ja/ChetanKhatri_1.md
> translate Chetan Khatri's abstract

- _candidates_ja/ZahariDichev_3.md
> translate Zahari Dichev's abstract

- _candidates_ja/WilberChao_1.md
fix #487 
CFP内に日本語も含まれていたが、英語側と合わないような感じの部分があったので意訳している。
ただ、英語側よりも（私の英語力もあれだが）日本語側のほうが言いたいことがわかるような部分もあるので、
もしかしたら英語もそこまで得意ではないのかも…？
何れにしても「Unitテストに自分で書いた型クラスを適応することで、型クラス（の作り方）を学ぼうぜ！！！」感だと思うで…それが伝われば…
> add WilberChao_1 ja

- _candidates_ja/WilberChao_2.md
> add Wilberchao_2 ja

- _candidates_ja/MahmoudAbdelghany_1.md
> translate Mahmoud Abdelghany's abstract

- _candidates_ja/FlavioBrasil_1.md
> translate Flavio Brasil's abstract

- _candidates_ja/MikhailMutcianko_1.md
> translate Mikhail Mutcianko's abstract

- _candidates_ja/PiotrGawrys_1.md
> translate Piotr Gawryś's abstract

- _candidates_ja/JoanGoyeau_1.md
> add JoanGoyeau_1 ja

- _candidates_ja/Taylor_1.md
https://github.com/scalajp/2019.scalamatsuri.org/issues/146 の日本語訳です。
> translate Taylor's abstract

- _candidates_ja/ZachMcCoy_1.md
https://github.com/scalajp/2019.scalamatsuri.org/issues/305 の日本語訳です。
> translate Zach McCoy's first abstract

- _candidates_ja/SahilSawhney_1.md
> translate Sahil Sawhney's abstract

- _candidates_ja/KrzysztofOtrebski_1.md
> translate Krzysztof Otrębski's abstract

- _candidates_ja/SebastienDoeraene_2.md
> translate Sébastien Doeraene's second abstract

- _candidates_ja/SebastienDoeraene_1.md
> translate Sébastien Doeraene's abstract

- _candidates_ja/MatanKeidar_1.md
> translate Matan Keidar's abstract

- _candidates_ja/AlexanderKonovalov_2.md
> translate Alexander Konovalov's abstract

- _candidates_ja/ColtFrederickson_2.md
Fixes #480 (issue番号修正しました by OE)
> translate Colt Frederickson's second abstract

- _candidates_en/kmizu_1.md
> touch up Mizushima-san's abtract

- _candidates_en/kmizu_1.md
Ref https://github.com/scalajp/2019.scalamatsuri.org/pull/773
> some typo fix on Mizushima-san's abtract

- _candidates_en/ChanglinLi_1.md
- _candidates_en/KenichiTanga_1.md
- _candidates_en/kmizu_1.md
> Fix issue 185

- _candidates_ja/JoanGoyeau_1.md
原題は「Scala 3, what does it means for me?」で、「私」のニュアンスがabstract上かなり重要という話になったので、修正します。
https://github.com/scalajp/2019.scalamatsuri.org/blob/442fff8d1dd2034e5957f599afb1d59fbf79284d/_candidates_en/JoanGoyeau_1.md
> fix Joan's proposal title translation

- _candidates_ja/RubenResino_2.md
> fix file path

- ja/candidates/index.html
復活してしまっていたので、消します。
英語の方は出た無いです。
> 私もなにか話したいが復活していたのでコメントアウト

- en/candidates/index.html
- ja/candidates/index.html
- js/cfp-voting.js
> (do not merge) セッションの投票機能をOFFに

- _data/nav_en.yml
- _data/nav_ja.yml
- en/travel/index.html
- ja/travel/index.html
> add travel info

- _data/logos/utage.yml
- _data/nav_en.yml
- _data/nav_ja.yml
- _data/program_en.yml
- _data/program_ja.yml
- _includes/program/day0.html
- _includes/program/day1.html
- _includes/program/day2.html
- _includes/program/section.html
- _includes/program/utage.html
- index.html
- index_en.html
> タイムテーブルの公開

- _includes/schedule_en.html
- _includes/schedule_ja.html
> Update language and audience

- _includes/index/en/info.html
- _includes/index/ja/info.html
> Fix tickets menu

- _data/program_en.yml
- _data/program_ja.yml
> registration opens at 9:20

- _data/program_en.yml
- _data/program_ja.yml
- _includes/program/day1.html
スライドに日本語が含まれている旨のメッセージを追加
ref: #867
> Add disclaimer

- _includes/program/section.html
- index.html
- index_en.html
Reverts scalajp/2019.scalamatsuri.org#880
> Revert "Modify 一時的にアンカンファレンスのみ表示するように変更"

- _candidates_en/FlavioBrasil_1.md
- _candidates_en/JoanGoyeau_1.md
- _candidates_en/JulienTournay_1.md
- _candidates_en/SahilSawhney_1.md
- _candidates_en/SebastienDoeraene_2.md
- _candidates_en/kmizu_1.md
- _candidates_ja/FlavioBrasil_1.md
- _candidates_ja/JoanGoyeau_1.md
- _candidates_ja/JulienTournay_1.md
- _candidates_ja/SahilSawhney_1.md
- _candidates_ja/SebastienDoeraene_2.md
- _candidates_ja/kmizu_1.md
これでカンファレンスパートの全てスライドのリンクを貼り終わった感じでしょうか？
> complete adding conference slide urls

- _data/nav_en.yml
- _data/nav_ja.yml
- _data/staff.yml
- en/commercial/index.html
> Add staff list
